name: Release
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies And Build
        run: |
          npm install
          npm run build

      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'release/*.bobplugin'
          token: ${{ secrets.GITHUB_TOKEN }}
